// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUliByPz2xN98CX0rkljlTT-MhNBnTynU',
    appId: '1:673918876374:web:a2b67e246ce50539726777',
    messagingSenderId: '673918876374',
    projectId: 'cmsc23-todo-app-llocampo2',
    authDomain: 'cmsc23-todo-app-llocampo2.firebaseapp.com',
    storageBucket: 'cmsc23-todo-app-llocampo2.appspot.com',
    measurementId: 'G-HDLRY3SZ8X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZvun8wdDdCi1ltWg4L7Yh4VqO1ni2e1c',
    appId: '1:673918876374:android:5bcd305dfbfa5bb0726777',
    messagingSenderId: '673918876374',
    projectId: 'cmsc23-todo-app-llocampo2',
    storageBucket: 'cmsc23-todo-app-llocampo2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA60qMs_gdOYBKIMAomD39e0YYVeyTM4Yw',
    appId: '1:673918876374:ios:73f28ddd80c60d39726777',
    messagingSenderId: '673918876374',
    projectId: 'cmsc23-todo-app-llocampo2',
    storageBucket: 'cmsc23-todo-app-llocampo2.appspot.com',
    iosClientId: '673918876374-djur3nokp86eesccqunnabpq7nm6lbgg.apps.googleusercontent.com',
    iosBundleId: 'com.example.week7NetworkingDiscussion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA60qMs_gdOYBKIMAomD39e0YYVeyTM4Yw',
    appId: '1:673918876374:ios:73f28ddd80c60d39726777',
    messagingSenderId: '673918876374',
    projectId: 'cmsc23-todo-app-llocampo2',
    storageBucket: 'cmsc23-todo-app-llocampo2.appspot.com',
    iosClientId: '673918876374-djur3nokp86eesccqunnabpq7nm6lbgg.apps.googleusercontent.com',
    iosBundleId: 'com.example.week7NetworkingDiscussion',
  );
}
